import type { Candidate } from "../interfaces/Candidate.interface";

// Prop types generated by copilot GPT4
type SavedCandidatesProps = {
    savedCandidates: Candidate[];
    setSavedCandidates: React.Dispatch<React.SetStateAction<Candidate[]>>;
};

const SavedCandidates = () => {
  return (
    <>
      <h1>Potential Candidates</h1>
    </>
  );
};

export default SavedCandidates;
